// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StocksApp.Infrastructure;

#nullable disable

namespace StocksApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005075512_AddSellOrderMatching")]
    partial class AddSellOrderMatching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StocksApp.Domain.Entities.BuyOrder", b =>
                {
                    b.Property<Guid>("BuyOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .HasColumnType("text");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BuyOrderID");

                    b.HasIndex("UserId");

                    b.ToTable("BuyOrder", null, t =>
                        {
                            t.HasCheckConstraint("CK_BuyOrder_Price", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_BuyOrder_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.Candle1m", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "BucketStart");

                    b.ToTable("candles_1m", (string)null);
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.CandleMatch5s", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "BucketStart");

                    b.ToTable("candle_matches_5s", (string)null);
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.CandleMatchFlushBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("candle_match_flush_backup", (string)null);
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.Outbox", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OutboxId");

                    b.ToTable("Outbox", (string)null);
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.SellOrder", b =>
                {
                    b.Property<Guid>("SellOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StockName")
                        .HasColumnType("text");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SellOrderID");

                    b.HasIndex("UserId");

                    b.HasIndex("StockSymbol", "ActivatesAt")
                        .HasDatabaseName("ix_sellorders_pending_symbol")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("SellOrder", null, t =>
                        {
                            t.HasCheckConstraint("CK_SellOrder_Price", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_SellOrder_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.TrackedSymbol", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Symbol");

                    b.ToTable("TrackedSymbols", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrackedSymbols_Symbol_Upper", "\"Symbol\" = upper(\"Symbol\")");
                        });
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_CashBalance_NonNegative", "\"CashBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.BuyOrder", b =>
                {
                    b.HasOne("StocksApp.Domain.Entities.User", "User")
                        .WithMany("BuyOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.SellOrder", b =>
                {
                    b.HasOne("StocksApp.Domain.Entities.User", "User")
                        .WithMany("SellOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StocksApp.Domain.Entities.User", b =>
                {
                    b.Navigation("BuyOrders");

                    b.Navigation("SellOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
