/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#005047",
        "surface-container-highest": "#2d3449",
        "on-secondary": "#233143",
        "inverse-on-surface": "#283044",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary-fixed": "#00201c",
        "on-error": "#690005",
        "on-tertiary": "#003731",
        "on-secondary-container": "#a7b6cc",
        "inverse-primary": "#494bd6",
        "surface-container-high": "#222a3d",
        secondary: "#b9c8de",
        "primary-fixed": "#e1e0ff",
        "surface-bright": "#31394d",
        background: "#0b1326",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#0d0096",
        "on-secondary-fixed": "#0d1c2d",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#d4e4fa",
        "surface-container": "#171f33",
        tertiary: "#3cddc7",
        "surface-tint": "#c0c1ff",
        "on-primary": "#1000a9",
        "surface-dim": "#0b1326",
        "on-secondary-fixed-variant": "#39485a",
        "error-container": "#93000a",
        surface: "#0b1326",
        "on-primary-fixed": "#07006c",
        "outline-variant": "#464554",
        "surface-container-lowest": "#060e20",
        primary: "#c0c1ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface": "#dae2fd",
        "secondary-container": "#39485a",
        "tertiary-container": "#008678",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#b9c8de",
        "on-tertiary-container": "#000705",
        "inverse-surface": "#dae2fd",
        "on-background": "#dae2fd",
        "primary-container": "#8083ff",
        "tertiary-fixed": "#62fae3",
        "tertiary-fixed-dim": "#3cddc7",
        outline: "#908fa0",
        "surface-variant": "#2d3449",
        "on-primary-fixed-variant": "#2f2ebe",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        sm: "8px",
        unit: "4px",
        lg: "24px",
        xl: "40px",
        "container-max": "1280px",
        xs: "4px",
        gutter: "20px",
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-code": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
