apiVersion: v1
kind: Secret
metadata:
  name: webapi-secrets
  namespace: ${DEPLOY_NAMESPACE}
type: Opaque
stringData:
  JWT__Key: "${JWT_KEY}"
  FinnhubApiKey: "${WEBAPI_FINNHUB_API_KEY}"
  RabbitMQ__UserName: "${RABBITMQ_USER}"
  RabbitMQ__Password: "${RABBITMQ_PASSWORD}"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}"
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
  namespace: ${DEPLOY_NAMESPACE}
type: Opaque
stringData:
  JWT__Key: "${JWT_KEY}"
  FinnhubApiKey: "${WORKER_FINNHUB_API_KEY}"
  RabbitMQ__UserName: "${RABBITMQ_USER}"
  RabbitMQ__Password: "${RABBITMQ_PASSWORD}"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}"