apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-worker
  namespace: ${DEPLOY_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-worker
  template:
    metadata:
      labels:
        app: orders-worker
    spec:
      containers:
        - name: ordersworker
          image: ghcr.io/${REPO_OWNER}/stocksapp.ordersworker:${IMAGE_TAG}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: stocksapp-config
            - secretRef:
                name: worker-secrets