apiVersion: v1
kind: Service
metadata:
  name: stocksapp-frontend-service
  namespace: ${DEPLOY_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: stocksapp-frontend
  ports:
  - port: 80
    targetPort: 80