apiVersion: v1
kind: Service
metadata:
  name: stocksapp-webapi-service
  namespace: ${DEPLOY_NAMESPACE}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: stocksapp-webapi