name: CI Pipeline

on:
  pull_request:
    branches: [ main, dev, staging ]
  push:
    branches: [ main, dev, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running Unit & Integration tests stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: './StocksAppSolution/StocksAppSolution.sln'

      - name: Restore dependencies
        run: dotnet restore ./StocksAppSolution/StocksAppSolution.sln

      - name: Build solution
        run: dotnet build ./StocksAppSolution/StocksAppSolution.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ./StocksAppSolution/StocksAppSolution.sln --no-build --configuration Release --verbosity normal